# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml

loki:
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
  auth_enabled: false
minio:
  enabled: true
