# https://github.com/minio/minio/blob/master/helm/minio/values.yaml
buckets:
  - name: chunks
    policy: none
    purge: false
  - name: ruler
    policy: none
    purge: false
  - name: admin
    policy: none
    purge: false
  - name: loki
    policy: none
    purge: false

replicas: 1

persistence:
  size: 50Gi

mode: standalone
